#%%

DB_PATH = "result/mlruns.db"
ARTIFACT_LOCATION = "result/artifacts"
EXPERIMENT_NAME = "test_mlflow"
Phi2_MAX_TOKENS = 2048
Phi2_OUTPUT_FILE = "phi-2 select.json"

# VRTCL_DELIM = ","
VRTCL_DELIM = ""
HRZNTL_DELIM = "\n"
FAKE_NUM = 9
TRUE_NUM = 1
CANDIDATE_NUM = FAKE_NUM + TRUE_NUM
INOUT_CANDIDATE_NUM = int(CANDIDATE_NUM / 2)
